---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Sync apt cache
      ansible.builtin.apt:
        cache_valid_time: 3600
        update_cache: true
      register: _pre_update_apt_cache
      until: _pre_update_apt_cache is succeeded
      when:
        - ansible_pkg_mgr == "apt"
    - name: Install netstat on Fedora
      ansible.builtin.package:
        name: net-tools
        state: present
      when:
        - ansible_pkg_mgr == "dnf"
