---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Check if coturn package is installed
      ansible.builtin.fail:
        msg: "coturn package not installed"
      when: "'coturn' not in ansible_facts.packages"

    - name: Check if coturn service is running
      ansible.builtin.fail:
        msg: "coturn service is not running"
      when: "'coturn.service' not in ansible_facts.services or ansible_facts.services['coturn.service'].state != 'running'"

    - name: Check port 3478
      ansible.builtin.wait_for:
        port: 3478

    - name: Check port 3479
      ansible.builtin.wait_for:
        port: 3479